    

server:
 port: 9090
 
spring:
 application:
  name: banking-alstrom-app

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


 datasource:
        driverClassName: oracle.jdbc.driver.OracleDriver
        password: root
        url: jdbc:oracle:thin:@10.120.68.217:1521:xe
        username: system
 jpa:
        properties:
            hibernate:
                boot:
                    allow_jdbc_metadata_access: false
                dialect: org.hibernate.dialect.OracleDialect


#jpa
management:
    endpoints:
        web:
            exposure:
                include: '*'

eureka:
 client:
  fetch-registry: true    
